version: '3.9'

services:

  app:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0

  server:
    build: ./backend
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:14-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"